"""update_db

Revision ID: d8157a9990d3
Revises: b4d5b9d35e8d
Create Date: 2025-07-11 10:40:00.514575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8157a9990d3'
down_revision: Union[str, Sequence[str], None] = 'b4d5b9d35e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmarks_short_code'), table_name='bookmarks')
    op.create_index('ix_bookmarks_short_code', 'bookmarks', ['short_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookmarks_short_code', table_name='bookmarks')
    op.create_index(op.f('ix_bookmarks_short_code'), 'bookmarks', ['short_code'], unique=True)
    # ### end Alembic commands ###
